# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Buy SDK Advanced Sample' do
    use_frameworks!
    pod 'OptimizelySDKiOS', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
    pod 'OptimizelySDKDatafileManager', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
    pod 'OptimizelySDKEventDispatcher', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
    pod 'OptimizelySDKUserProfileService', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
    pod 'OptimizelySDKShared', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
    pod 'OptimizelySDKCore', :git => 'https://github.com/optimizely/objective-c-sdk.git', :branch => 'master'
end
